### ISSUE TITLE
[FEATURE] Add a static `SessionManager` class to Pancake

### ISSUE THREAD

**Issue by guibranco** [guibranco/pancake#234]
**Description:**
I would like to add a `SessionManager` class to the Pancake toolkit library in PHP. The class should act as a static wrapper around PHP's built-in session management functions, providing an easy-to-use interface for handling session operations. 

The `SessionManager` should handle tasks like starting sessions, setting, getting, and removing session data, and regenerating session IDs. The class will ensure that the session is started only when needed, reducing unnecessary overhead. Below is an example implementation:

```php
<?php

namespace GuiBranco\Pancake;

class SessionManager
{
    public static function start()
    {
        if (session_status() == PHP_SESSION_NONE) {
            session_start();
        }
    }

    public static function set($key, $value)
    {
        self::start();
        $_SESSION[$key] = $value;
    }

    public static function get($key, $default = null)
    {
        self::start();
        return $_SESSION[$key] ?? $default;
    }

    public static function has($key)
    {
        self::start();
        return isset($_SESSION[$key]);
    }

    public static function remove($key)
    {
        self::start();
        unset($_SESSION[$key]);
    }

    public static function destroy()
    {
        if (session_status() != PHP_SESSION_NONE) {
            session_unset();
            session_destroy();
        }
    }

    public static function regenerate()
    {
        if (session_status() != PHP_SESSION_NONE) {
            session_regenerate_id(true);
        }
    }
}
```

This class will provide a convenient interface for session handling and improve the Pancake library's overall functionality.

**Acceptance Criteria:**
- The `SessionManager` class is implemented and included in the Pancake toolkit.
- Unit tests are provided to ensure that the class behaves as expected.
- Documentation is updated to include usage examples of the `SessionManager`.

**Comment by guibranco** [comment]
@gstraccini create labels

**Comment by Humayun-23** [comment]
Hello, I want to work on this issue, please assign me this.

**Comment by guibranco** [comment]
Hi @Humayun-23 ,

Thanks for picking this up! 🙌
You have been assigned the issue.

If you have any questions or need clarification along the way, feel free to ask.

Good luck and happy coding! 😊
